services:
  neovim:
    build:
      context: ./src/platforms/${NEOVIM_NAME}/generated
      dockerfile: Dockerfile
    container_name: neovim-${NEOVIM_NAME}
    environment:
      UID: ${NEOVIM_UID}
      GID: ${NEOVIM_GID}
    volumes:
      - ${NEOVIM_MNT_DIR}:/mnt/project
      - neovim:/home/node/.local/share
        #- ./custom.sh:/home/node/custom.sh
    hostname: neovim-${NEOVIM_NAME}
volumes:
  neovim: {}