#! /usr/bin/bash

NODES=$(sh $PWD/src/constants/nodes.sh)
IMAGE=$(sh $PWD/src/constants/image.sh)

NODES_ARR=($(echo $NODES | tr "," "\n"))

START_SH="#! /usr/bin/bash"
GENERATED_MESS="# Generated by script. Don't change it manually!"

for node in "${NODES_ARR[@]}"
do  
    platform_path=$PWD/src/platforms/$node
    common_path=$PWD/src/common
    generated_path=$platform_path/generated
    dockerfile_path=$generated_path/Dockerfile
    init_path=$generated_path/init.sh
    init_vim_path=$generated_path/init.vim
    entrypoint_path=$generated_path/entrypoint.sh

    mkdir -p $generated_path

    echo "Creating '$node' files to path: $platform_path"

    echo $GENERATED_MESS > $dockerfile_path
    echo '' >> $dockerfile_path
    echo "$(cat $common_path/Dockerfile.head.snippet)" >> $dockerfile_path
    echo '' >> $dockerfile_path
    echo "########## Platform specified part ##########" >> $dockerfile_path
    echo "$(cat $platform_path/Dockerfile | sed "s/$IMAGE//g")" >> $dockerfile_path
    echo "#############################################" >> $dockerfile_path
    echo '' >> $dockerfile_path
    echo "$(cat $common_path/Dockerfile.body.snippet | sed "s/$IMAGE//g")" >> $dockerfile_path

    echo $START_SH > $init_path
    echo $GENERATED_MESS >> $init_path
    echo "$(cat $common_path/init.snippet.head.sh)" >> $init_path
    echo '' >> $init_path
    echo "########## Platform specified part ##########" >> $init_path
    echo "$(cat $platform_path/init.sh)" >> $init_path
    echo "#############################################" >> $init_path
    echo '' >> $init_path
    echo "$(cat $common_path/init.snippet.body.sh)" >> $init_path

    echo $START_SH > $entrypoint_path
    echo $GENERATED_MESS >> $entrypoint_path
    echo "$(cat $common_path/entrypoint.sh)" >> $entrypoint_path

    echo "\" $GENERATED_MESS" > $init_vim_path
    echo "$(cat $common_path/init.vim)" >> $init_vim_path
done
