services:
  neovim:
    image: kolserdav/coc-nvim-${NEOVIM_NAME}
    container_name: neovim-${NEOVIM_NAME}
    environment:
      UID: ${NEOVIM_UID}
      GID: ${NEOVIM_GID}
    volumes:
      - ${NEOVIM_MNT_DIR}:/mnt/project
      - neovim-${NEOVIM_NAME}:/home/node/.local/share
        #- ./custom.sh:/home/node/custom.sh
    hostname: neovim-${NEOVIM_NAME}
volumes:
  neovim-${NEOVIM_NAME}: {}