FROM node:bookworm-slim

COPY init.vim $XDG_CONFIG_HOME/nvim/init.vim
RUN nvim -c "PlugInstall --sync | qa"

COPY init.sh $HOME/init.sh
COPY entrypoint.sh $HOME/entrypoint.sh

ENV PATH=$PATH:$NPM_CONFIG_PREFIX/bin

WORKDIR $MNT_DIR

ENTRYPOINT ["sh", "/home/node/entrypoint.sh"]
CMD ["sh", "/home/node/init.sh"]