FROM node:bookworm-slim

COPY init.sh $HOME/init.sh
COPY entrypoint.sh $HOME/entrypoint.sh
COPY init.vim $XDG_CONFIG_HOME/nvim/init.vim
RUN sudo chown $NVIM_USER:$NVIM_USER $HOME/*

RUN nvim -c "PlugInstall --sync | qa"

WORKDIR $MNT_DIR

ENTRYPOINT ["sh", "/home/node/entrypoint.sh"]
CMD ["sh", "/home/node/init.sh"]
