services:
  neovim:
    image: kolserdav/coc-nvim-python
    container_name: neovim-python
    environment:
      UID: ${NEOVIM_UID}
      GID: ${NEOVIM_GID}
    volumes:
      - ${NEOVIM_MNT_DIR}:/mnt/project
      - neovim-python:/home/node/.local/share
        #- ./custom.sh:/home/node/custom.sh
    hostname: neovim-python
volumes:
  neovim-python: {}
