services:
  neovim:
    image: kolserdav/coc-nvim-node
    container_name: neovim-node
    environment:
      UID: ${NEOVIM_UID}
      GID: ${NEOVIM_GID}
    volumes:
      - ${NEOVIM_MNT_DIR}:/mnt/project
      - neovim-node:/home/node/.local/share
        #- ./custom.sh:/home/node/custom.sh
    hostname: neovim-node
volumes:
  neovim-node: {}
